import json
import os
import time
from typing import List, Dict, Any

# Path to the mapping file
MAPPING_FILE = os.path.join(os.path.dirname(__file__), "sample-data", "specmatch-mapping.json")

class DemoSpecMatchStub:
    def __init__(self):
        self.mappings = self._load_mappings()

    def _load_mappings(self) -> List[Dict[str, Any]]:
        if not os.path.exists(MAPPING_FILE):
            print(f"Warning: Mapping file not found at {MAPPING_FILE}")
            return []
        with open(MAPPING_FILE, "r") as f:
            return json.load(f)

    def process_pdf(self, file_path: str) -> Dict[str, Any]:
        """
        Simulates processing a PDF.
        If the filename matches one in our mapping, return deterministic results.
        Otherwise, return a generic fallback result.
        """
        filename = os.path.basename(file_path)
        
        # Simulate processing delay
        time.sleep(1.5) 

        # Find match
        for item in self.mappings:
            if item["filename"] == filename:
                return {
                    "status": "success",
                    "filename": filename,
                    "matches": item["matches"],
                    "metadata": item.get("extracted_metadata", {}),
                    "audit_log": [
                        f"{time.ctime()}: File uploaded.",
                        f"{time.ctime()}: Text extracted (simulated).",
                        f"{time.ctime()}: SpecMatch Engine found {len(item['matches'])} matches."
                    ]
                }
        
        # Fallback for unknown files
        return {
            "status": "success",
            "filename": filename,
            "matches": [
                {
                    "sku": "GENERIC-STUB-ITEM",
                    "name": "Generic Detected Item",
                    "confidence": 0.5,
                    "reason": "Demo mode: Unknown file uploaded. Using fallback stub.",
                    "category": "General"
                }
            ],
            "metadata": {"note": "Generated by Demo Stub"},
            "audit_log": [f"{time.ctime()}: File processed by Fallback Stub."]
        }

specmatch_engine = DemoSpecMatchStub()
