import { AppLayout } from '@/components/layout/AppLayout';
import { KPICard } from '@/components/common/KPICard';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useApp } from '@/context/AppContext';
import { monthlyAnalytics, weeklyRFPData } from '@/data/mockData';
import { FileText, Target, Clock, Edit, Bot } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell, Legend } from 'recharts';

const matchDistribution = [
  { name: '≥90%', value: 45, color: 'hsl(142, 76%, 36%)' },
  { name: '80-90%', value: 35, color: 'hsl(38, 92%, 50%)' },
  { name: '<80%', value: 20, color: 'hsl(0, 84%, 60%)' },
];

const monthlyTrend = [
  { month: 'Aug', rfps: 18, match: 85 },
  { month: 'Sep', rfps: 22, match: 87 },
  { month: 'Oct', rfps: 20, match: 88 },
  { month: 'Nov', rfps: 25, match: 89 },
  { month: 'Dec', rfps: 24, match: 91 },
  { month: 'Jan', rfps: 28, match: 93 },
];

export default function Reports() {
  const { dashboardStats } = useApp();
  
  return (
    <AppLayout title="Reports & Analytics">
      <div className="space-y-6">
        {/* KPI Cards */}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <KPICard
            title="RFPs This Month"
            value={monthlyAnalytics.rfpsProcessed}
            subtitle="Total processed"
            icon={FileText}
            trend={{ value: 15, positive: true }}
          />
          <KPICard
            title="Avg SpecMatch"
            value={`${monthlyAnalytics.avgSpecMatch}%`}
            subtitle="Product match accuracy"
            icon={Target}
            trend={{ value: 4, positive: true }}
          />
          <KPICard
            title="Avg Turnaround"
            value={`${monthlyAnalytics.avgTurnaround}h`}
            subtitle="Response time"
            icon={Clock}
            trend={{ value: 12, positive: true }}
          />
          <KPICard
            title="Auto-Generated"
            value={`${Math.round((monthlyAnalytics.autoGenerated / monthlyAnalytics.rfpsProcessed) * 100)}%`}
            subtitle={`${monthlyAnalytics.autoGenerated} of ${monthlyAnalytics.rfpsProcessed} responses`}
            icon={Bot}
          />
        </div>

        {/* Charts Row 1 */}
        <div className="grid gap-6 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Monthly RFP Volume</CardTitle>
              <CardDescription>Number of RFPs processed per month</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={monthlyTrend}>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                    <XAxis dataKey="month" className="text-xs" />
                    <YAxis className="text-xs" />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: 'hsl(var(--card))',
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px',
                      }}
                    />
                    <Bar dataKey="rfps" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} name="RFPs Processed" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base">SpecMatch % Trend</CardTitle>
              <CardDescription>Average match percentage over time</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={monthlyTrend}>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                    <XAxis dataKey="month" className="text-xs" />
                    <YAxis className="text-xs" domain={[80, 100]} />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: 'hsl(var(--card))',
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px',
                      }}
                    />
                    <Line
                      type="monotone"
                      dataKey="match"
                      stroke="hsl(142, 76%, 36%)"
                      strokeWidth={2}
                      dot={{ fill: 'hsl(142, 76%, 36%)' }}
                      name="Avg SpecMatch %"
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Charts Row 2 */}
        <div className="grid gap-6 lg:grid-cols-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Match Distribution</CardTitle>
              <CardDescription>Line items by match quality</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={matchDistribution}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={90}
                      paddingAngle={2}
                      dataKey="value"
                    >
                      {matchDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip
                      contentStyle={{
                        backgroundColor: 'hsl(var(--card))',
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px',
                      }}
                    />
                    <Legend />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>

          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle className="text-base">Response Generation Stats</CardTitle>
              <CardDescription>Auto-generated vs manually edited responses</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="flex items-center gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                    <Bot className="h-6 w-6 text-primary" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium">Auto-Generated</span>
                      <span className="text-sm text-muted-foreground">{monthlyAnalytics.autoGenerated} responses</span>
                    </div>
                    <div className="h-2 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full bg-primary rounded-full"
                        style={{ width: `${(monthlyAnalytics.autoGenerated / monthlyAnalytics.rfpsProcessed) * 100}%` }}
                      />
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-amber-100">
                    <Edit className="h-6 w-6 text-amber-600" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium">Manually Edited</span>
                      <span className="text-sm text-muted-foreground">{monthlyAnalytics.manualEdited} responses</span>
                    </div>
                    <div className="h-2 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full bg-amber-500 rounded-full"
                        style={{ width: `${(monthlyAnalytics.manualEdited / monthlyAnalytics.rfpsProcessed) * 100}%` }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </AppLayout>
  );
}
